name: Criar nova release

env:
  plugin_name: buy-champions

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths:
      - index.js
      - README.md
      - README.br.md

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zipando o plugin
        run: zip -r ${{ env.plugin_name }}.zip index.js README.md README.br.md

      - name: Criando a release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.plugin_name }} v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: ${{ env.plugin_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
